### ISSUE TITLE
Issue when compiling with images 

### ISSUE THREAD

**Issue by Andy-Can** [AndrewAtLarge/WebQuiz#14]
I have a LaTex file with two image dependancies (fig_1.png , fig2_2.png).

When I run `webquiz [myTexFile]' without those images in my web server directory, the quiz compiles fine, albeit without including the images on the webpage.

When I include the images and compile the webquix I get the following error:

<img width="527" alt="Screen Shot 2020-05-19 at 11 40 23 AM" src="https://user-images.githubusercontent.com/65306284/82348022-53662980-99c6-11ea-965e-e1fb98e26a4f.png">
 

The images are included when I typeset on my local machine (using pdfLaTex).

**Comment by AndrewAtLarge** [comment]
Can you please post a _minimal example file_ that demonstrates the problem so that I can trouble shoot? That is, I'd like a small LaTeX file that when run through WebQuiz produces the error above. Rather than using your actual images you could try using the `mwe` package. So something like:
```
\documentclass{webquiz}
\usepackage{graphicx}
\usepackage{mwe}% for example images
\begin{document}
\begin{question}
  \includegraphics{example-image}
\end{question}
\end{document}
```

Can you also please tell me what operating system you are using and what happens when you compile your LaTeX file with `webquiz --debugging <filename>`.

**Comment by Andy-Can** [comment]
I am working on a Linux Server

Minimal Example File:
```
\documentclass{webquiz}
\usepackage{graphicx}
\usepackage{mwe}% for example images
\begin{document}
	\begin{question}
	\includegraphics{example-image}
	Test Question
  		\begin{choice}[columns=1] % multiple choice question
			\correct True 
			\incorrect False 
 		\end {choice}
	\end{question}
\end{document}

```

Output when debugging (same output on MWE file):
<img width="522" alt="Screen Shot 2020-05-21 at 11 18 16 AM" src="https://user-images.githubusercontent.com/65306284/82574312-e46b0b00-9b54-11ea-9b18-7d57bbd3efd5.png">

<img width="527" alt="Screen Shot 2020-05-21 at 11 18 24 AM" src="https://user-images.githubusercontent.com/65306284/82574296-dfa65700-9b54-11ea-845c-db3da21e0667.png">

**Comment by Andy-Can** [comment]
Any ideas/updates on this? The images are in the same directory as my .tex file. Also received this error message.
![Screen Shot 2020-06-18 at 10 38 16 AM](https://user-images.githubusercontent.com/65306284/85034326-f938bf80-b14f-11ea-9737-b2a24e826bf5.png)

**Comment by webquiz** [comment]
I am sorry but I am completely flat out at the moment with my day job and I will probably not have to look at this properly until August. I can't reproduce your error. Are your image files in the same directory as the tex file?

It would help if you posted the actual output from the debugging command `webquiz --debugging signals`. Please do not post a screenshot and instead cut and paste _all_ of the output from `webquiz -q --debugging signals`. Above you have written `<signals>` for the filename, but the less and greater sign characters redirect input and output in linux so please do not use these.

**Comment by Andy-Can** [comment]
Totally understand! Attached is the complete output. Yes, the images are in the same directory. I know the program is finding them, because when I run "make webquiz" the first image disappears from the directory. This leads me to believe the issue is in my config settings. 
```
adsager@vhosts:/w/216online/WebQuiz/signals$ ls
Q6.png	Q8.png	signals.tex
adsager@vhosts:/w/216online/WebQuiz/signals$ webquiz -q --debugging signals.tex
WebQuiz generating web page for signals.tex
Processing signals.tex with TeX4ht
----------------------------------------
WebQuiz error:
  makequiz: something went wrong when running htlatex on signals
----------------------------------------

File: /usr/lib/python3.5/codecs.py, line number: 501
Error 'utf-8' codec can't decode byte 0x89 in position 30: invalid start byte in read: newchars, decodedbytes = self.decode(data, self.errors)
----------------------------------------
WebQuiz error:
  unknown problem.

If you think this is a bug please report it by creating an issue at
    github.com/AndrewAtLarge/WebQuiz/issues

----------------------------------------

File: /usr/lib/python3.5/codecs.py, line number: 501
Error 'utf-8' codec can't decode byte 0x89 in position 30: invalid start byte in read: newchars, decodedbytes = self.decode(data, self.errors)
Traceback (most recent call last):
  File "/usr/bin/webquiz", line 1124, in <module>
    .format(metadata.repository), err)
  File "/usr/bin/webquiz", line 1082, in <module>
    webquiz_makequiz.MakeWebQuiz(quiz_name, quiz_file, options, settings, metadata)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 60, in __init__
    self.htlatex_quiz_file()
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 237, in htlatex_quiz_file
    self.webquiz_error( 'something went wrong when running htlatex on {}'.format(self.quiz_file), err)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 104, in webquiz_error
    webquiz_util.webquiz_error(self.settings.debugging, 'makequiz: '+msg, err)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 220, in htlatex_quiz_file
    for line in make4ht_file:
  File "/usr/lib/python3.5/codecs.py", line 711, in __next__
    return next(self.reader)
  File "/usr/lib/python3.5/codecs.py", line 642, in __next__
    line = self.readline()
  File "/usr/lib/python3.5/codecs.py", line 555, in readline
    data = self.read(readsize, firstline=True)
  File "/usr/lib/python3.5/codecs.py", line 501, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 30: invalid start byte
adsager@vhosts:/w/216online/WebQuiz/signals$ 
```

**Comment by webquiz** [comment]
It's an encoding issue. Are you able to replace the file 

/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py

with the file [webquiz_makequiz.py](maths.usyd.edu.au/u/mathas/webquiz_makequiz.py) and let me know if this makes any difference.

**Comment by Andy-Can** [comment]
I will try this tomorrow, have to wait for administrator access, as it won't let me change it. Will update you.
Thanks again.

**Comment by Andy-Can** [comment]
Syntax Error:
```
adsager@vhosts:/w/216online/WebQuiz/signals$ ls
Q6.png	 signals.4ct  signals.dvi   signals.lg	 signals.tmp
Q8.png	 signals.4tc  signals.html  signals.log  signals.xml
signals  signals.aux  signals.idv   signals.tex  signals.xref
adsager@vhosts:/w/216online/WebQuiz/signals$ webquiz signals.tex
Traceback (most recent call last):
  File "/usr/bin/webquiz", line 31, in <module>
    import webquiz_makequiz
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 66
    language_file = webquiz_util.kpsewhich(f'webquiz-{self.quiz.language}.lang')
                                                                              ^
SyntaxError: invalid syntax

```

**Comment by webquiz** [comment]
What version of python do you have installed? You can check with `python3 --version`. It looks like you have 3.5, or earlier, as f-strings were introduced in 3.6. The current version is 3.8.3.

**Comment by Andy-Can** [comment]
2.7. Good catch, I'll update you if that does the trick.

**Comment by webquiz** [comment]
It looks like you probably tested `python --version` whereas you want `python3 --version`. Python 2 has been on the way out for years and is now, finally, depreciated -- even though it is still very much in use. Webquiz uses python3 and won't run with python 2.

**Comment by Andy-Can** [comment]
Right Again --- 3.5.2.

**Comment by Andy-Can** [comment]
I've updated python, and ran webquiz again -- here it the output

```
adsager@vhosts:/w/216online/WebQuiz$ ls
css  js        webquiz1.4ct  webquiz1.aux  webquiz1.html  webquiz1.lg	webquiz1.tex  webquiz1.xml
doc  webquiz1  webquiz1.4tc  webquiz1.dvi  webquiz1.idv   webquiz1.log	webquiz1.tmp  webquiz1.xref
adsager@vhosts:/w/216online/WebQuiz$ webquiz -q --debugging webquiz1
WebQuiz generating web page for webquiz1.tex
Processing webquiz1.tex with TeX4ht
cmd=make4ht --config webquiz.cfg     webquiz1.tex
xml: Starting tag for webquiz
xml: Just set "debugging" equal to "false" from "false"
xml: Just set "hide_side_menu" equal to "false" from "DeFaUlT"
xml: Just set "language" equal to "english" from "DeFaUlT"
xml: Just set "one_page" equal to "false" from "DeFaUlT"
xml: Just set "pst2pdf" equal to "false" from "false"
xml: Just set "random_order" equal to "false" from "DeFaUlT"
xml: Just set "src" equal to "webquiz1.tex" from "webquiz1.tex"
xml: Just set "theme" equal to "default" from "DeFaUlT"
xml: Starting tag for title
xml: ending tag for title (should be title)
xml: Starting tag for breadcrumb
xml: Just set "breadcrumbs" equal to "" from "DeFaUlT"
xml: ending tag for breadcrumb (should be breadcrumb)
xml: Starting tag for unit_name
xml: Just set "unit_url" equal to "" from ""
xml: ending tag for unit_name (should be unit_name)
xml: Starting tag for unit_code
xml: ending tag for unit_code (should be unit_code)
xml: Starting tag for department
xml: Just set "department" equal to "" from "DeFaUlT"
xml: ending tag for department (should be department)
xml: Just set "department" equal to "" from " 
DeFaUlT"
xml: Starting tag for institution
xml: Just set "institution" equal to "" from "DeFaUlT"
xml: ending tag for institution (should be institution)
xml: Just set "institution" equal to "" from " 
DeFaUlT"
----------------------------------------
WebQuiz error:
  xml: unknown fatal error
----------------------------------------

File: /usr/local/lib/python3.6/xml/sax/expatreader.py, line number: 217
Error webquiz1.xml:11:61: not well-formed (invalid token) in feed: self._parser.Parse(data, isFinal)
----------------------------------------
WebQuiz error:
  makequiz: error reading the xml generated for webquiz1. Please check your latex source.
----------------------------------------

File: /usr/local/lib/python3.6/xml/sax/expatreader.py, line number: 217
Error not well-formed (invalid token): line 11, column 61 in feed: self._parser.Parse(data, isFinal)
----------------------------------------
WebQuiz error:
  unknown problem.

If you think this is a bug please report it by creating an issue at
    github.com/AndrewAtLarge/WebQuiz/issues

----------------------------------------

File: /usr/local/lib/python3.6/xml/sax/expatreader.py, line number: 217
Error not well-formed (invalid token): line 11, column 61 in feed: self._parser.Parse(data, isFinal)
Traceback (most recent call last):
  File "/usr/bin/webquiz", line 1124, in <module>
    .format(metadata.repository), err)
  File "/usr/bin/webquiz", line 1082, in <module>
    webquiz_makequiz.MakeWebQuiz(quiz_name, quiz_file, options, settings, metadata)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 62, in __init__
    self.read_xml_file()
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 247, in read_xml_file
    .format(self.quiz_name), err)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 102, in webquiz_error
    webquiz_util.webquiz_error(self.settings.debugging, 'makequiz: '+msg, err)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 244, in read_xml_file
    self.quiz = webquiz_xml.ReadWebQuizXmlFile(self.quiz_name + '.xml', self.settings)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_xml.py", line 36, in ReadWebQuizXmlFile
    parser.parse(quizfile)
  File "/usr/local/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/local/lib/python3.6/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_xml.py", line 386, in fatalError
    self.webquiz_error('unknown fatal error', e)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_xml.py", line 114, in webquiz_error
    webquiz_util.webquiz_error(self.defaults.debugging, 'xml: '+msg, err)
  File "/usr/local/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 11, column 61
adsager@vhosts:/w/216online/WebQuiz$ webquiz -q --debugging webquiz1
```

**Comment by Andy-Can** [comment]
I've tried compiling the example webquiz file (which originally worked) and got a similar error message. Did we potentially break something with the new webquiz_makequiz.py?

`Error test.xml:11:61: not well-formed (invalid token) in feed: self._parser.Parse(data, isFinal)`

**Comment by AndrewAtLarge** [comment]
Sorry, the file that I gave you was a modified version of the `webquiz_makequiz.py` file from the development version, which may not be compatible with the rest of the files that you have. I have replaced the file on my server with one that is a modified version of the official release. When I tried to test this I also found issues with `kpsewhich`, which appears to have been updated, so you may need to download and install both of the following files:

- [webquiz_makequiz.py](https://www.maths.usyd.edu.au/u/mathas/webquiz_makequiz.py)
- [webquiz.py](https://www.maths.usyd.edu.au/u/mathas/webquiz.py)

Please let me know if this is any better.

**Comment by Andy-Can** [comment]
Now just getting "Permission Denied"
```
adsager@vhosts:/w/216online/WebQuiz$ cd /usr/share/texlive/texmf-dist/scripts/webquiz/
adsager@vhosts:/usr/share/texlive/texmf-dist/scripts/webquiz$ ls
CHANGES.rst  README-scripts  webquiz_layout.py	  webquiz_templates.py
LICENCE      webquiz	     webquiz_makequiz.py  webquiz_util.py
__pycache__  webquiz.bat     webquiz.py		  webquiz_xml.py
adsager@vhosts:/usr/share/texlive/texmf-dist/scripts/webquiz$ cd /w/216online/WebQuiz/
adsager@vhosts:/w/216online/WebQuiz$ ls
css	 test.4ct   test.idv  test.xml	    webquiz1.aux   webquiz1.log
doc	 test.4tc   test.lg   test.xref     webquiz1.dvi   webquiz1.tex
js	 test.aux   test.log  webquiz1	    webquiz1.html  webquiz1.tmp
signals  test.dvi   test.tex  webquiz1.4ct  webquiz1.idv   webquiz1.xml
test	 test.html  test.tmp  webquiz1.4tc  webquiz1.lg    webquiz1.xref
adsager@vhosts:/w/216online/WebQuiz$ webquiz test
-bash: /usr/bin/webquiz: Permission denied
```

**Comment by AndrewAtLarge** [comment]
The file `webquiz.py` needs to be executable. Probably you just need `chmod +x webquiz.py` or `sudo chmod +x webquiz.py`. If this doesn't work check that the the symbolic link from `webquiz` still points to `webquiz.py`. If you are using bash, you can check the link using `ls -l $(which webquiz)`.

**Comment by Andy-Can** [comment]
Still not working with images. Error output similar to before:
```
adsager@vhosts:/w/216online/WebQuiz/image_test$ ls
Q6.png		    signals_images.aux	 signals_images.log
Q8.png		    signals_images.dvi	 signals_images.tex
signals_images	    signals_images.html  signals_images.tmp
signals_images.4ct  signals_images.idv	 signals_images.xml
signals_images.4tc  signals_images.lg	 signals_images.xref
adsager@vhosts:/w/216online/WebQuiz/image_test$ webquiz -q --debugging signals_images
WebQuiz generating web page for signals_images.tex
Processing signals_images.tex with TeX4ht
xml: Starting tag for webquiz
xml: Just set "debugging" equal to "false" from "false"
xml: Just set "hide_side_menu" equal to "false" from "DeFaUlT"
xml: Just set "language" equal to "english" from "DeFaUlT"
xml: Just set "one_page" equal to "false" from "DeFaUlT"
xml: Just set "pst2pdf" equal to "false" from "false"
xml: Just set "random_order" equal to "false" from "DeFaUlT"
xml: Just set "src" equal to "signals_images.tex" from "signals_images.tex"
xml: Just set "theme" equal to "default" from "DeFaUlT"
xml: Starting tag for title
xml: ending tag for title (should be title)
xml: Starting tag for breadcrumb
xml: Just set "breadcrumbs" equal to "" from "DeFaUlT"
xml: ending tag for breadcrumb (should be breadcrumb)
xml: Starting tag for unit_name
xml: Just set "unit_url" equal to "" from ""
xml: ending tag for unit_name (should be unit_name)
xml: Starting tag for unit_code
xml: ending tag for unit_code (should be unit_code)
xml: Starting tag for department
xml: Just set "department" equal to "" from "DeFaUlT"
xml: ending tag for department (should be department)
xml: Just set "department" equal to "" from " 
DeFaUlT"
xml: Starting tag for institution
xml: Just set "institution" equal to "" from "DeFaUlT"
xml: ending tag for institution (should be institution)
xml: Just set "institution" equal to "" from " 
DeFaUlT"
xml: Starting tag for meta
xml: ending tag for meta (should be meta)
xml: Starting tag for meta
xml: ending tag for meta (should be meta)
xml: Starting tag for meta
xml: ending tag for meta (should be meta)
xml: Starting tag for meta
xml: ending tag for meta (should be meta)
xml: Starting tag for meta
xml: ending tag for meta (should be meta)
xml: Starting tag for link
xml: ending tag for link (should be link)
xml: Starting tag for a
xml: ending tag for a (should be a)
xml: Starting tag for question
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: Starting tag for choice
xml: Starting tag for a
xml: ending tag for a (should be a)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: Starting tag for feedback
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for feedback (should be feedback)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: Starting tag for feedback
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for feedback (should be feedback)
xml: ending tag for choice (should be choice)
xml: ending tag for question (should be question)
xml: Starting tag for a
xml: ending tag for a (should be a)
xml: Starting tag for question
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: Starting tag for choice
xml: Starting tag for a
xml: ending tag for a (should be a)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: ending tag for choice (should be choice)
xml: ending tag for question (should be question)
xml: Starting tag for a
xml: ending tag for a (should be a)
xml: Starting tag for question
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: Starting tag for choice
xml: Starting tag for a
xml: ending tag for a (should be a)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: ending tag for choice (should be choice)
xml: ending tag for question (should be question)
xml: Starting tag for a
xml: ending tag for a (should be a)
xml: Starting tag for question
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: Starting tag for choice
xml: Starting tag for a
xml: ending tag for a (should be a)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: ending tag for choice (should be choice)
xml: ending tag for question (should be question)
xml: Starting tag for a
xml: ending tag for a (should be a)
xml: Starting tag for question
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: Starting tag for choice
xml: Starting tag for a
xml: ending tag for a (should be a)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: Starting tag for item
xml: Starting tag for text
xml: ending tag for text (should be text)
xml: ending tag for item (should be item)
xml: ending tag for choice (should be choice)
xml: ending tag for question (should be question)
xml: Starting tag for a
xml: ending tag for a (should be a)
xml: Starting tag for question
xml: Starting tag for text
----------------------------------------
WebQuiz error:
  xml: unknown fatal error
----------------------------------------

File: /usr/local/lib/python3.6/xml/sax/expatreader.py, line number: 217
Error signals_images.xml:316:0: not well-formed (invalid token) in feed: self._parser.Parse(data, isFinal)
----------------------------------------
WebQuiz error:
  makequiz: error reading the xml generated for signals_images. Please check your latex source.
----------------------------------------

File: /usr/local/lib/python3.6/xml/sax/expatreader.py, line number: 217
Error not well-formed (invalid token): line 316, column 0 in feed: self._parser.Parse(data, isFinal)
----------------------------------------
WebQuiz error:
  unknown problem.

If you think this is a bug please report it by creating an issue at
    github.com/AndrewAtLarge/WebQuiz/issues

----------------------------------------

File: /usr/local/lib/python3.6/xml/sax/expatreader.py, line number: 217
Error not well-formed (invalid token): line 316, column 0 in feed: self._parser.Parse(data, isFinal)
Traceback (most recent call last):
  File "/usr/bin/webquiz", line 1095, in <module>
    .format(metadata.repository), err)
  File "/usr/bin/webquiz", line 1053, in <module>
    webquiz_makequiz.MakeWebQuiz(quiz_name, quiz_file, options, settings, metadata)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 62, in __init__
    self.read_xml_file()
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 251, in read_xml_file
    .format(self.quiz_name), err)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 104, in webquiz_error
    webquiz_util.webquiz_error(self.settings.debugging, 'makequiz: '+msg, err)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_makequiz.py", line 248, in read_xml_file
    self.quiz = webquiz_xml.ReadWebQuizXmlFile(self.quiz_name + '.xml', self.settings)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_xml.py", line 36, in ReadWebQuizXmlFile
    parser.parse(quizfile)
  File "/usr/local/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/local/lib/python3.6/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_xml.py", line 386, in fatalError
    self.webquiz_error('unknown fatal error', e)
  File "/usr/share/texlive/texmf-dist/scripts/webquiz/webquiz_xml.py", line 114, in webquiz_error
    webquiz_util.webquiz_error(self.defaults.debugging, 'xml: '+msg, err)
  File "/usr/local/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 316, column 0
adsager@vhosts:/w/216online/WebQuiz/image_test$ ls
signals_images	    signals_images.html  signals_images.tmp
signals_images.4ct  signals_images.idv	 signals_images.xml
signals_images.4tc  signals_images.lg	 signals_images.xref
signals_images.aux  signals_images.log
signals_images.dvi  signals_images.tex
adsager@vhosts:/w/216online/WebQuiz/image_test$
```

**Comment by AndrewAtLarge** [comment]
I can't reproduce this: for me the test file compiles without problem. What version and distribution of tex do you have? Probably the easiest way to find this is using `pdflatex --version`.

**Comment by Andy-Can** [comment]
```
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian)
kpathsea version 6.2.1
```
I mentioned this before, but could it be related to my initialization settings? Because I do not have sudoer access on the server, I chose the  "save to the user rcfile" option. 

I very much appreciate your help.

**Comment by AndrewAtLarge** [comment]
Sorry, I certainly should have asked this first as this is almost certainly the source of all of your problems. As it says in the manual, `webquiz` requires TeXLive 2019 or later.

**Comment by Andy-Can** [comment]
I've had the administrator install the 2020 version. It now compiles without issue, but I am getting this junk output (even on webquizes without images). Any ideas?
<img width="1384" alt="Screen Shot 2020-07-02 at 9 57 29 AM" src="https://user-images.githubusercontent.com/65306284/86368073-c3650200-bc4a-11ea-9e58-8b61b59b71c4.png">

**Comment by Andy-Can** [comment]
It looks like this bug is already documented. I will close this thread on monitor the other one.
